env:
  browser: true
  es2021: true
extends: 'airbnb-base'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - 'app/javascript/entrypoints/vendor/**'
  - 'app/javascript/**/*.css'
  - 'app/javascript/**/*.scss'
  - 'app/javascript/images/*'
  - 'app/javascript/fonts/*'
globals:
  $: readonly
  isOrcid: readonly # TODO: Clean this up by using ESM import/export.
rules:
  no-console:   # OK: console.log is fine for debugging, but we don't want to keep it around indefinitely.
    - error     # Also make sure that warnings and errors are marked as such.
    - { allow: ["warn", "error"] }
