default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 40)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: <%= ENV["lando_database_conn_host"] || "localhost" %>
  port: <%= ENV["lando_database_conn_port"] || 5432 %>
  username: <%= ENV["lando_database_creds_user"] %>
  password: <%= ENV["lando_database_creds_password"] %>
  database: <%= ENV['APP_DB'] %>

development:
  <<: *default
  database: <%= ENV["lando_pdc_orcid_creds_database"] || ENV["APP_DB"] || 'pdc_orcid_dev' %>

test:
  <<: *default
  database: <%= ENV["lando_pdc_orcid_creds_database"] || ENV["APP_DB"] || 'pdc_orcid_test' %>

production:
  <<: *default

staging:
  <<: *default